import Vue from 'vue';
import Vuex from 'vuex';
import { fetchKoreaData, fetchGlobalData } from '@/api';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    // KOREA STATE
    localeSynthesize: [],
    localeOptions: [
      { name: '서울', locale: 'seoul' },
      { name: '부산', locale: 'busan' },
      { name: '충북', locale: 'chungbuk' },
      { name: '충남', locale: 'chungnam' },
      { name: '대구', locale: 'daegu' },
      { name: '대전', locale: 'daejeon' },
      { name: '강원', locale: 'gangwon' },
      { name: '광주', locale: 'gwangju' },
      { name: '경북', locale: 'gyeongbuk' },
      { name: '경기', locale: 'gyeonggi' },
      { name: '경남', locale: 'gyeongnam' },
      { name: '인천', locale: 'incheon' },
      { name: '제주', locale: 'jeju' },
      { name: '전북', locale: 'jeonbuk' },
      { name: '전남', locale: 'jeonnam' },
      { name: '세종', locale: 'sejong' },
      { name: '울산', locale: 'ulsan' },
      { name: '검역', locale: 'quarantine' },
    ],

    // GLOBAL STATE
    nationSynthesize: [],
    nationOptions: [
      { name: 'Etc.', nation: 'etc' },
      { name: '코모로', nation: 'comoros' },
      { name: '상투메 프린시페', nation: 'sainttomeprincipe' },
      { name: '남수단', nation: 'southsudan' },
      { name: '말라위', nation: 'malawi' },
      { name: '시에라리온', nation: 'sierraleone' },
      { name: '브룬디', nation: 'burundi' },
      { name: '보츠와나', nation: 'botswana' },
      { name: '말리', nation: 'marley' },
      { name: '기니비사우', nation: 'guineabissau' },
      { name: '모잠비크', nation: 'mozambique' },
      { name: '우간다', nation: 'uganda' },
      { name: '에리트레아', nation: 'eritrea' },
      { name: '앙골라', nation: 'angola' },
      { name: '마다가스카르', nation: 'madagascar' },
      { name: '짐바브웨', nation: 'zimbabwe' },
      { name: '카보베르데', nation: 'capeverde' },
      { name: '소말리아', nation: 'somalia' },
      { name: '니제르', nation: 'niger' },
      { name: '차드', nation: 'chad' },
      { name: '잠비아', nation: 'zambia' },
      { name: '감비아', nation: 'gambia' },
      { name: '모리셔스', nation: 'mauritius' },
      { name: '지부티', nation: 'djibouti' },
      { name: '탄자니아', nation: 'tanzania' },
      { name: '라이베리아', nation: 'liberia' },
      { name: '베냉', nation: 'benin' },
      { name: '세이쉘', nation: 'seychelles' },
      { name: '르완다', nation: 'rwanda' },
      { name: '모리타니아', nation: 'mauritania' },
      { name: '에스와티니', nation: 'eswatini' },
      { name: '적도기니', nation: 'guinea' },
      { name: '콩고', nation: 'congo' },
      { name: '중앙아프리카공화국', nation: 'centralafricanrepublic' },
      { name: '나미비아', nation: 'namibia' },
      { name: '케냐', nation: 'kenya' },
      { name: '기니', nation: 'guineaecuatorial' },
      { name: '가나', nation: 'ghana' },
      { name: '가봉', nation: 'gabon' },
      { name: '에티오피아', nation: 'ethiopia' },
      { name: '수단', nation: 'sudan' },
      { name: '코트디부아르', nation: 'ivorycoast' },
      { name: 'DR콩고', nation: 'drcongo' },
      { name: '부르키나파소', nation: 'burkinafaso' },
      { name: '토고', nation: 'republiquetogolaise' },
      { name: '남아프리카공화국', nation: 'republicofsouthafrica' },
      { name: '카메룬', nation: 'cameroon' },
      { name: '세네갈', nation: 'senegal' },
      { name: '나이지리아', nation: 'nigeria' },
      { name: '파푸아뉴기니', nation: 'papuanewguinea' },
      { name: '피지', nation: 'fiji' },
      { name: '뉴질랜드', nation: 'newzealand' },
      { name: '호주', nation: 'australia' },
      { name: '코소보', nation: 'kosovo' },
      { name: '몬테네그로', nation: 'montenegro' },
      { name: '터키', nation: 'turkey' },
      { name: '사이프러스', nation: 'cyprus' },
      { name: '알바니아', nation: 'albania' },
      { name: '몰도바', nation: 'moldova' },
      { name: '몰타', nation: 'malta' },
      { name: '불가리아', nation: 'bulgaria' },
      { name: '슬로바키아', nation: 'slovakia' },
      { name: '세르비아', nation: 'serbia' },
      { name: '리히텐슈타인', nation: 'liechtenstein' },
      { name: '슬로베니아', nation: 'slovenija' },
      { name: '보스니아 헤르체고비나', nation: 'bosnaihercegovina' },
      { name: '헝가리', nation: 'hungary' },
      { name: '우크라이나', nation: 'ukraine' },
      { name: '폴란드', nation: 'poland' },
      { name: '안도라', nation: 'andora' },
      { name: '라트비아', nation: 'latvia' },
      { name: '포르투갈', nation: 'portugal' },
      { name: '체코', nation: 'czecho' },
      { name: '아일랜드', nation: 'ireland' },
      { name: '아르메니아', nation: 'armenia' },
      { name: '룩셈부르크', nation: 'luxembourg' },
      { name: '모나코', nation: 'monaco' },
      { name: '아이슬란드', nation: 'iceland' },
      { name: '아제르바이잔', nation: 'azerbaijan' },
      { name: '산마리노', nation: 'sanmarino' },
      { name: '리투아니아', nation: 'lithuania' },
      { name: '벨라루스', nation: 'belarus' },
      { name: '네덜란드', nation: 'nederlands' },
      { name: '루마니아', nation: 'romania' },
      { name: '노르웨이', nation: 'norway' },
      { name: '북마케도니아', nation: 'macedonia' },
      { name: '그리스', nation: 'greece' },
      { name: '조지아', nation: 'georgia' },
      { name: '에스토니아', nation: 'eesti' },
      { name: '덴마크', nation: 'danmark' },
      { name: '벨기에', nation: 'belgium' },
      { name: '스위스', nation: 'swiss' },
      { name: '스웨덴', nation: 'sweden' },
      { name: '핀란드', nation: 'finland' },
      { name: '크로아티아', nation: 'croatia' },
      { name: '오스트리아', nation: 'austria' },
      { name: '스페인', nation: 'spain' },
      { name: '영국', nation: 'england' },
      { name: '프랑스', nation: 'france' },
      { name: '독일', nation: 'germany' },
      { name: '이탈리아', nation: 'italiana' },
      { name: '세인트키츠네비스', nation: 'saintkittsandnevis' },
      { name: '도미니카연방', nation: 'dominicanfederation' },
      { name: '벨리즈', nation: 'belize' },
      { name: '그레나다', nation: 'grenada' },
      { name: '아이티', nation: 'haiti' },
      { name: '니카라구아', nation: 'nicaragua' },
      { name: '바베이도스', nation: 'barbados' },
      { name: '엘살바도르', nation: 'elsalvador' },
      { name: '바하마', nation: 'bahamas' },
      { name: '과테말라', nation: 'guatemala' },
      { name: '수리남', nation: 'suriname' },
      { name: '세인트루시아', nation: 'saintlucia' },
      { name: '우루과이', nation: 'uruguay' },
      { name: '트리니다드토바고', nation: 'trinidadandtobago' },
      { name: '앤티가바부다', nation: 'antiguaandbarbuda' },
      { name: '베네수엘라', nation: 'venezuela' },
      { name: '가이아나', nation: 'guyana' },
      { name: '쿠바', nation: 'cuba' },
      { name: '세인트빈센트그레나딘', nation: 'stvincentandthegrenadines' },
      { name: '온두라스', nation: 'honduras' },
      { name: '자메이카', nation: 'jamaica' },
      { name: '볼리비아', nation: 'bolivia' },
      { name: '파나마', nation: 'panama' },
      { name: '파라과이', nation: 'paraguay' },
      { name: '코스타리카', nation: 'costarica' },
      { name: '페루', nation: 'peru' },
      { name: '콜롬비아', nation: 'columbia' },
      { name: '칠레', nation: 'chile' },
      { name: '아르헨티나', nation: 'argentina' },
      { name: '도미니카공화국', nation: 'dominican' },
      { name: '에콰도르', nation: 'ecuador' },
      { name: '멕시코', nation: 'mexico' },
      { name: '브라질', nation: 'brasil' },
      { name: '캐나다', nation: 'canada' },
      { name: '미국', nation: 'usa' },
      { name: '예멘', nation: 'yemen' },
      { name: '리비아', nation: 'libya' },
      { name: '시리아', nation: 'syria' },
      { name: '모로코', nation: 'morocco' },
      { name: '사우디아라비아', nation: 'saudiarabia' },
      { name: '튀니지', nation: 'tunisia' },
      { name: '요르단', nation: 'jordan' },
      { name: '카타르', nation: 'qatar' },
      { name: '알제리', nation: 'algeria' },
      { name: '이집트', nation: 'egypt' },
      { name: '이스라엘', nation: 'israel' },
      { name: '레바논', nation: 'lebanon' },
      { name: '오만', nation: 'oman' },
      { name: '이라크', nation: 'iraq' },
      { name: '아랍에미리트', nation: 'uae' },
      { name: '바레인', nation: 'bahrain' },
      { name: '쿠웨이트', nation: 'kuwait' },
      { name: '이란', nation: 'iran' },
      { name: '타지키스탄', nation: 'tajikistan' },
      { name: '라오스', nation: 'laos' },
      { name: '미얀마', nation: 'myanmar' },
      { name: '동티모르', nation: 'easttimor' },
      { name: '키르기스스탄', nation: 'kyrgyzstan' },
      { name: '우즈베키스탄', nation: 'uzbekistan' },
      { name: '카자흐스탄', nation: 'kazakhstan' },
      { name: '몽골', nation: 'mongolia' },
      { name: '브루나이', nation: 'brunei' },
      { name: '방글라데시', nation: 'bangladesh' },
      { name: '몰디브', nation: 'maldives' },
      { name: '부탄', nation: 'bhutan' },
      { name: '인도네시아', nation: 'indonesia' },
      { name: '파키스탄', nation: 'pakistan' },
      { name: '아프가니스탄', nation: 'afghanistan' },
      { name: '스리랑카', nation: 'srilanka' },
      { name: '러시아', nation: 'russia' },
      { name: '네팔', nation: 'nepal' },
      { name: '캄보디아', nation: 'cambodia' },
      { name: '필리핀', nation: 'philippines' },
      { name: '인도', nation: 'india' },
      { name: '베트남', nation: 'vietnam' },
      { name: '말레이시아', nation: 'malaysia' },
      { name: '태국', nation: 'thailand' },
      { name: '싱가포르', nation: 'singapura' },
      { name: '일본', nation: 'japan' },
      { name: '마카오', nation: 'macau' },
      { name: '대만', nation: 'taiwan' },
      { name: '홍콩', nation: 'hongkong' },
      { name: '중국', nation: 'china' },
    ],
  },
  mutations: {
    SET_KOREA_SYNTHESIZE(state, data) {
      state.localeSynthesize = data;
    },
    SET_GLOBAL_SYNTHESIZE(state, data) {
      state.nationSynthesize = data;
    },
  },
  actions: {
    // 한국 총 확진자 조회
    async fetchKoreaSynthesize({ commit }) {
      const { data } = await fetchKoreaData('synthesize');
      commit('SET_KOREA_SYNTHESIZE', data.data[0]);
    },
    // 한국 도시별 확진자 조회
    async fetchKoreaLocale({ commit }, locale) {
      const { data } = await fetchKoreaData(locale);
      return data.data[0];
    },
    // 해외 총 확진자 조회
    async fetchGlobalSynthesize({ commit }) {
      const { data } = await fetchGlobalData('synthesize');
      commit('SET_GLOBAL_SYNTHESIZE', data.data[0]);
    },
    // 해외 나라별 확진자 조회
    async fetchGlobalNation({ commit }, nation) {
      const { data } = await fetchGlobalData(nation);
      return data.data[0];
    },
  },
});
